# Docker compose for MANAGEMENT SYSTEMS STUDENT
# Hosted in AWS using ElasticBeanstalk: http://managementsystemstudent-env.eba-jevqcxee.eu-west-2.elasticbeanstalk.com/

version : "3.8"
services:
  backend:
    #Image pulled from our docker hub
    image: "nickmonks94/management-system-student:latest"
    ports:
      - "80:8080"
    #Restart if any issues appear
    restart: "always"